"""Add user_id foreign key to food_entries

Revision ID: 0400b798f39d
Revises: 9770204f4c08
Create Date: 2025-05-07 12:51:51.204980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0400b798f39d'
down_revision = '9770204f4c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_fitness_entries_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_food_entries_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_info_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_info_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_food_entries_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_food_entries_user_id', 'users',['user_id'],['id'])


    with op.batch_alter_table('fitness_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fitness_entries_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
