"""Initial setup with nullable fields

Revision ID: 505bc6a90b05
Revises: 
Create Date: 2025-05-11 22:36:04.565916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505bc6a90b05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_entries', schema=None) as batch_op:
        batch_op.alter_column('activity_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('calories_burned',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.alter_column('food_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('calories',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('food_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('fitness_entries', schema=None) as batch_op:
        batch_op.alter_column('calories_burned',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('activity_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
