"""Security storing applied and share entry added

Revision ID: cb541a1e3d33
Revises: 0400b798f39d
Create Date: 2025-05-09 11:42:28.645948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb541a1e3d33'
down_revision = '0400b798f39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sharer_user_id', sa.Integer(), nullable=False),
    sa.Column('sharee_user_id', sa.Integer(), nullable=False),
    sa.Column('data_categories', sa.String(length=512), nullable=False),
    sa.Column('time_range', sa.String(length=64), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sharee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sharer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sharer_user_id', 'sharee_user_id', 'data_categories', 'time_range', name='_sharer_sharee_data_time_uc')
    )
    with op.batch_alter_table('fitness_entries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('fitness_entries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('share_entries')
    # ### end Alembic commands ###
